drop table IF EXISTS notes;

create TABLE IF NOT EXISTS notes (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  app VARCHAR(255) NOT NULL,
  uri VARCHAR(255) NOT NULL,
  ip VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);